apiVersion: v1
kind: ConfigMap
metadata:
  name: prom2teams-config
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.ini: |-
    [HTTP Server]
    Host: {{ .Values.prom2teams.host }}
    Port: {{ .Values.prom2teams.port }}
    [Microsoft Teams]
    Connector: {{ .Values.prom2teams.connector }}
    [Group Alerts]
    Field: {{ .Values.prom2teams.group_alerts_by }}
    [Log]
    Level: {{ .Values.prom2teams.loglevel }}
    [Template]
    Path: {{ .Values.prom2teams.templatepath }}
  #config.ini: {{ .Files.Get "files/config.ini" | quote }}
  teams.j2: {{ .Files.Get "files/teams.j2" |  quote }}
